# Generated by Django 5.1.1 on 2024-10-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Like'),
        ),
    ]
