# Generated by Django 5.1.1 on 2024-10-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rels', '0002_video_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hashteg',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Хэштег'),
        ),
    ]
